In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
import statistics

In [ ]:
Randomly generate 1,000 samples from the normal distribution using np.random.normal()(mean = 100, standard deviation = 15)

np.random.normal(loc=0.0, scale=1.0, size=None) #you need to modify this code.

loc will be equal to mean, scale will be equal to std deviation, size will be equal to sample size.

In [2]:
samples = np.random.normal(loc=100, scale=15, size=1000)

In [ ]:
Compute the mean, median, and mode

In [3]:
mean = np.mean(samples)
median =np.median(samples)
mode = stats.mode(samples)

print(f"Mean value of samples: {mean}")
print(f"Median value of samples: {median}")
print(f"Mode value of samples: {mode}")

Mean value of samples: 100.2810273092652
Median value of samples: 100.56507990689948
Mode value of samples: ModeResult(mode=array([54.1697717]), count=array([1]))


C:\Users\nazli\AppData\Local\Temp\ipykernel_7444\1617063908.py:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(samples)


In [ ]:
Mean value of samples: 100.07170248861537
Median value of samples: 100.02445064865117
Mode value of samples: ModeResult(mode=array([41.9474214]), count=array([1]))
Compute the min, max, Q1, Q3, and interquartile range

In [4]:
min = min(samples)
max = max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = q3 - q1

print(f"Min value of samples: {min}")
print(f"Max value of samples: {max}")
print(f"q1 value of samples: {q1}")
print(f"q3 value of samples: {q3}")
print(f"IQR value of samples: {iqr}")

Min value of samples: 54.16977169677949
Max value of samples: 157.3047955691329
q1 value of samples: 90.26574809757454
q3 value of samples: 110.34350821160879
IQR value of samples: 20.07776011403425


In [ ]:
Compute the variance and standard deviation

In [5]:
variance = statistics.variance(samples)
std_dev = statistics.stdev(samples)
print(f"Variance : {variance}")
print(f"standeart devision: {std_dev}")

Variance : 219.73840211613847
standeart devision: 14.823575888298292


In [6]:
#np.std(samples)
#np.var(samples)

In [ ]:
Compute the skewness and kurtosis

You can use scipy.stats.skew and scipy.stats.kurtosis

In [8]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)
print("Skewness", skewness)
print("Kurtosis", kurtosis)

Skewness 0.04203971059579237
Kurtosis 0.05874828335683446


In [ ]:
NumPy Correlation Calculation

In [9]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
Then use np.array() to create a second array y containing 10 arbitrary integers.

In [10]:
y = np.array([1, 3, 5, 6, 8, 5, 7, 6, 9, 10])
y

array([ 1,  3,  5,  6,  8,  5,  7,  6,  9, 10])

In [ ]:
Once you have two arrays of the same length, you can compute the correlation coefficient between x and y

In [11]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.86732334],
       [0.86732334, 1.        ]])

In [ ]:
Pandas Correlation Calculation


In [13]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [14]:
stats.pearsonr(x, y) # Pearson's r

PearsonRResult(statistic=0.758640289091187, pvalue=0.010964341301680815)

In [15]:
from scipy.stats import spearmanr

In [16]:
rho = spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

In [17]:
stats.spearmanr(x, y)   # Spearman's rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

In [ ]:
Seaborn Dataset Tips

In [19]:
import seaborn as sns

In [20]:
tips = sns.load_dataset("tips")

In [21]:
tips.mode()

total_bill  tip   sex smoker  day    time  size
0       13.42  2.0  Male     No  Sat  Dinner     2

In [22]:
tips.median(numeric_only= True)

total_bill    17.795
tip            2.900
size           2.000
dtype: float64

In [23]:
tips.corr(method="pearson")

C:\Users\nazli\AppData\Local\Temp\ipykernel_7444\341950967.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  tips.corr(method="pearson")


total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000